flask_app/chat/routes.py
import base64
import datetime
import openai
import uuid

from flask import Blueprint, render_template, flash, redirect, url_for, session
from flask_login import login_required, current_user
from mongoengine.queryset.visitor import Q

from ..forms import InitiateChatForm, SendChatForm
from ..models import AIChatContext, AIChatMessage, load_user
from ..util import queries_mongodb
from ..client.openai_api import ChatSession

from .. import max_text_per_day

chat_blueprint = Blueprint('chat', __name__)

@chat_blueprint.route('/chat', defaults={'username': None}, methods=['GET'])
@chat_blueprint.route('/chat/<username>', methods=['GET'])
@queries_mongodb
def chat(username):
    if username:
        user = load_user(username)
        if not user:
            return render_template('404.html', message=f"User '{username}' does not exist."), 404
        chat_contexts = AIChatContext.objects(creator=user).order_by('-created')
        chats = ((context, AIChatMessage.objects(context=context).order_by('+created')) for context in chat_contexts)
    else:
        chat_contexts = AIChatContext.objects().order_by('-created')[:10]
        chats = ((context, AIChatMessage.objects(context=context).order_by('+created')) for context in chat_contexts)
    return render_template('chat.html', username=username, chats=chats if chat_contexts else [])

@chat_blueprint.route('/end_chat', methods=['GET'])
@login_required
def end_chat():
    session.pop('chat_id', None)
    return redirect(url_for('chat.chat_create'))

@chat_blueprint.route('/resume_chat/<id>', methods=['GET'])
@login_required
@queries_mongodb
def resume_chat(id):
    session['chat_id'] = uuid.UUID(id)
    return redirect(url_for('chat.chat_create'))

@chat_blueprint.route('/chat_create', methods=['GET', 'POST'])
@login_required
@queries_mongodb
def chat_create():
    current_context_id = session.get('chat_id', None)
    d = datetime.datetime.now() - datetime.timedelta(days=1)
    # https://docs.mongoengine.org/guide/querying.html

    user_contexts = AIChatContext.objects(creator=current_user._get_current_object())
    chats_within_one_day = sum(([x for x in AIChatMessage.objects(Q(context=context) & Q(created__gte=d) & Q(role='user'))] for context in user_contexts), [])

    next_use = None
    if (len(chats_within_one_day) >= max_text_per_day):
        next_use = min(chats_within_one_day, key=lambda x: x.created).created + datetime.timedelta(days=1)

    # This doubles as validation since we save the id as a cookie, clients can theoretically change it
    current_context = next((x for x in user_contexts if x.uuid == current_context_id), None) if current_context_id else None
    current_messages = [x for x in AIChatMessage.objects(context=current_context).order_by('+created')] if current_context else []

    init_form = InitiateChatForm()
    chat_form = SendChatForm()

    if init_form.validate_on_submit() and not current_context and not next_use:
        context = AIChatContext(
            uuid = uuid.uuid4(),
            creator = current_user._get_current_object(),
            context = init_form.prompt.data,
            created = datetime.datetime.now()
        )
        context.save()
        session['chat_id'] = context.uuid
        current_context = context
    elif chat_form.validate_on_submit() and current_context and not next_use:
        chat_session = ChatSession.from_models(current_context, current_messages)
        message = chat_form.message.data
        outgoing_message = AIChatMessage(
            context = current_context,
            role = 'user',
            content = message,
            created = datetime.datetime.now()
        )
        outgoing_message.save()
        
        try:
            result = chat_session.get_chat_completion(message)
            incoming_message = AIChatMessage(
                context = current_context,
                role = 'assistant',
                content = result,
                created = datetime.datetime.now()
            )
            incoming_message.save()
            current_messages.append(outgoing_message)
            current_messages.append(incoming_message)
        except openai.OpenAIError:
            flash('Oh no! Failed to query the OpenAI API. Please try again later.')

    return render_template('chat_create.html', init_form=init_form, chat_form=chat_form, uses=max_text_per_day - len(chats_within_one_day), next_use=next_use, current_context=current_context, current_messages=current_messages)

flask_app/image/routes.py
import base64
import datetime
import openai
import uuid

from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from mongoengine.queryset.visitor import Q

from ..forms import ImageCreateForm
from ..models import AIImage, load_user
from ..util import queries_mongodb
from ..client.openai_api import generate_image

from .. import max_images_per_day


image_blueprint = Blueprint('image', __name__)

@image_blueprint.route('/image', defaults={'username': None}, methods=['GET'])
@image_blueprint.route('/image/<username>', methods=['GET'])
@queries_mongodb
def image(username):
    if username:
        user = load_user(username)
        if not user:
            return render_template('404.html', message=f"User '{username}' does not exist."), 404
        images = AIImage.objects(creator=user).order_by('-created')
    else:
        images = AIImage.objects().order_by('-created')[:10]
    return render_template('image.html', username=username, images=[(x.creator.username, x.prompt, base64.b64encode(x.raw.read()).decode(), x.created, x.uuid) for x in images])

@image_blueprint.route('/image_create', methods=['GET', 'POST'])
@login_required
@queries_mongodb
def image_create():
    d = datetime.datetime.now() - datetime.timedelta(days=1)
    # https://docs.mongoengine.org/guide/querying.html
    images_within_1_day = AIImage.objects(Q(creator=current_user._get_current_object()) & Q(created__gte=d))

    next_use = None
    if (len(images_within_1_day) >= max_images_per_day):
        next_use = min(images_within_1_day, key=lambda x: x.created).created + datetime.timedelta(days=1)

    form = ImageCreateForm()
    if form.validate_on_submit() and not next_use:
        try:
            image = generate_image(form.prompt.data)
            ai_image = AIImage(
                uuid = uuid.uuid4(),
                creator = current_user._get_current_object(),
                prompt = form.prompt.data,
                raw = image,
                created = datetime.datetime.now()
            )
            ai_image.save()

            return redirect(url_for('image.image_display', id=ai_image.uuid))
        except openai.OpenAIError:
            flash('Oh no! Failed to query the OpenAI API. Please try again later.')
    
    return render_template('image_create.html', uses=max_images_per_day - len(images_within_1_day), next_use=next_use, form=form)

@image_blueprint.route('/image_display/<id>', methods=['GET'])
@queries_mongodb
def image_display(id):

    try:
        input_uuid = uuid.UUID(id)
    except ValueError:
        return render_template('404.html', message='Bad UUID'), 404

    image = AIImage.objects(uuid=input_uuid).first()
    if not image:
        return render_template('404.html', message='Image does not exist'), 404

    return render_template('image_display.html', image=(image.creator.username, image.prompt, base64.b64encode(image.raw.read()).decode(), image.created), back='')

flask_app/user/routes.py
import datetime

from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from flask_login import current_user, login_user, login_required, logout_user
from mongoengine.queryset.visitor import Q

from .. import bcrypt
from ..forms import LoginForm, RegistrationForm, UpdateUsernameForm
from ..models import User, AIImage, AIChatContext, AIChatMessage
from ..util import queries_mongodb, redirect_dest

from .. import max_images_per_day, max_text_per_day


user = Blueprint('user', __name__)

@user.route("/register", methods=['GET', 'POST'])
@queries_mongodb
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.account'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()

        flash('Registration complete! Please log in.')
        return redirect(url_for('user.login'))
    
    return render_template('register.html', title="Register", form=form)


@user.route('/login', methods=['GET', 'POST'])
@queries_mongodb
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.account'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect_dest(fallback=url_for('user.account'))
        else:
            flash('Login failed. Check your username and/or password.')
            return redirect(url_for('user.login'))

    return render_template('login.html', title='Login', form=form)


@user.route('/account', methods=['GET', 'POST'])
@login_required
@queries_mongodb
def account():
    d = datetime.datetime.now() - datetime.timedelta(days=1)
    # https://docs.mongoengine.org/guide/querying.html
    images_within_1_day = AIImage.objects(Q(creator=current_user._get_current_object()) & Q(created__gte=d))
    user_contexts = AIChatContext.objects(creator=current_user._get_current_object())
    chats_within_one_day = sum(([x for x in AIChatMessage.objects(Q(context=context) & Q(created__gte=d) & Q(role='user'))] for context in user_contexts), [])
    
    next_image_use = None
    if (len(images_within_1_day) >= max_images_per_day):
        next_image_use = min(images_within_1_day, key=lambda x: x.created).created + datetime.timedelta(days=1)

    next_chat_use = None
    if (len(chats_within_one_day) >= max_text_per_day):
        next_chat_use = min(chats_within_one_day, key=lambda x: x.created).created + datetime.timedelta(days=1)

    form = UpdateUsernameForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.save()
        flash('Please log in again with your new username.')
        return redirect(url_for('user.login'))

    return render_template('account.html', form=form, image_uses=max_images_per_day - len(images_within_1_day), chat_uses=max_text_per_day - len(chats_within_one_day) ,next_image_use=next_image_use, next_chat_use=next_chat_use)


@user.route('/user/<username>', methods=['GET'])
@queries_mongodb
def user_page(username):
    user = User.objects(username=username)
    if not user:
        return render_template('404.html', message=f"user '{username}' does not exist.")
    return render_template('user.html', username=username)


@user.route("/logout")
@login_required
def logout():
    session.pop('chat_id', None)
    logout_user()
    return redirect(url_for('main.index'))

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h3>Hey, {{ current_user.username }}!</h3>
        <br>
        <p>Remaining image tokens: {{image_uses}}</p>
        <p>Remaining chat tokens: {{chat_uses}}</p>
        {% if next_image_use %}
        <p>Next image token generation: {{next_image_use.strftime("%B %d, %Y at %H:%M:%S")}}</p>
        {% endif %}
        {% if next_chat_use %}
        <p>Next chat token generation: {{next_chat_use.strftime("%B %d, %Y at %H:%M:%S")}}</p>
        {% endif %}
        <p><a href="{{ url_for('image.image', username=current_user.username) }}">Your images</a></p>
        <p><a href="{{ url_for('chat.chat', username=current_user.username) }}">Your chats</a></p>

        <div class="row">
            <div class="col">
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-info">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                <form method="POST" action="">
                    {{ form.csrf_token }}
                    
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}
                        {{ form.username(class="form-control form-control-md bg-dark text-white w-50") }}
                
                        {% if form.username.errors %}
                        <div class="alert alert-warning" role="alert">
                          {% for error in form.username.errors %}
                          <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                        {% endif %}
                    </div>
        
                    <div class="form-group">
                        {{ form.submit(class="form-control form-control-md bg-dark text-white w-50") }}
                    </div> 
                </form>
            </div>
        </div>

        <p><a href="{{ url_for('user.logout') }}">Log Out</a></p>
    </div>
</div>  
{% endblock %}>

flask_app/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
    
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>AI Hub</title>
    {% endif %}
</head>

<body>
    {% block header %}
    <h1>TEMPLATE</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/chat.html
{% extends "header.html" %}
{% block content %}

<h1>Chat with a bot!</h1>
<p>Create your own <a href="{{ url_for('chat.chat_create') }}">HERE!</a></p>

{% if username %}
<p>Chats created by user {{username}}:</p>
{% else %}
<p>Latest chats:</p>
{% endif %}
<br>
{% if chats %}
{% for chat in chats %}

<div class="chat-gallery gallery">
    <div class="chat-box">
        {% for message in chat[1]%}
        <p><b>{{ chat[0].creator.username if message.role == 'user' else 'Bot' }}</b>: {{ message.content }}</p>
        {% endfor %}
    </div>
    <div class="desc"><b>{{chat[0].context}}</b></div>
    <div class="desc">By: <a href="{{ url_for('user.user_page', username=chat[0].creator.username) }}">{{chat[0].creator.username}}</a> {% if chat[0].creator.username == current_user.username %}(<a href="{{ url_for('chat.resume_chat', id=chat[0].uuid) }}">resume</a>){% endif %}</div>
    <div class="desc">Created: {{chat[0].created.strftime("%B %d, %Y at %H:%M:%S")}}</div>
</div>

{% endfor %}
{% else %}
<p>Oops! Nothing yet!</p>
{% endif %}

{% endblock %}

flask_app/templates/chat_create.html
{% extends "header.html" %}
{% block content %}

<h1>Chat with an AI!</h1>
<br>
{% if next_use %}
<p>Out of uses! Come back at {{next_use.strftime("%B %d, %Y at %H:%M:%S")}}</p>
{% else %}
<p>Uses left: {{ uses }}</p>
{% endif %}

{% if not current_context %}
{% if not next_use %}
<p>Describe how this AI will behave. (Ex. You are a 17th century poet who responds to everything with poetry)</p>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form method="POST" action="">
            {{ init_form.csrf_token }}
            
            <div class="form-group">
                {{ init_form.prompt.label(class="form-control-label") }}
                {{ init_form.prompt(class="form-control form-control-md bg-dark text-white") }}
        
                {% if init_form.prompt.errors %}
                <div class="alert alert-warning" role="alert">
                  {% for error in init_form.prompt.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group">
                {{ init_form.submit(class="form-control form-control-md bg-dark text-white") }}
            </div> 
        </form>
    </div>
</div>
{% endif %}
{% else %}
<p><a href="{{ url_for('chat.end_chat') }}">End Chat</a></p>
<p>Chat with the AI you created! ({{ current_context.context }})</p>
<div class="row">
    <div class="col">
        <div class="chat-box" id="chat-box">
            {% for message in current_messages%}
            <p><b>{{ 'You' if message.role == 'user' else 'Bot' }}</b>: {{ message.content }}</p>
            {% endfor %}
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% if not next_use %}
        <form method="POST" action="" id="form">
            {{ chat_form.csrf_token }}
            
            <div class="form-group">
                {{ chat_form.message.label(class="form-control-label") }}
                {{ chat_form.message(class="form-control form-control-md bg-dark text-white", id="chat-input") }}
        
                {% if chat_form.message.errors %}
                <div class="alert alert-warning" role="alert">
                  {% for error in chat_form.message.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group" id="submit-container">
                {{ chat_form.submit(class="form-control form-control-md bg-dark text-white") }}
            </div> 
        </form>
        {% endif %}
    </div>
</div>

<script nonce="{{ csp_nonce() }}">
    window.onload = function() {
        document.getElementById('chat-input').value = '';
        const chatBox = document.getElementById('chat-box');
        chatBox.scrollTop = chatBox.scrollHeight;
        window.scrollTo(0, document.body.scrollHeight);
        document.getElementById('form').onsubmit = function() {
            {# I couldn't get bootstrap to work here for some reason #}
            document.getElementById('submit-container').innerHTML = '<div class="form-control form-control-md bg-dark text-white"><div class="loading mx-auto"></div></div>';
        };
    };
</script>
{% endif %}

{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navMenu">
    <a href="{{ url_for('main.index') }}">Home</a>
    <a href="{{ url_for('chat.chat') }}">Chat</a>
    <a href="{{ url_for('image.image') }}">Image</a>
    {% if current_user.username %}
    <a href="{{ url_for('user.account') }}">Account</a>
    {% else %}
    <a href="{{ url_for('user.login') }}">Login</a>
    {% endif %}
</nav>

<div class="container">
    <hr class="navDiv">
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

flask_app/templates/image.html
{% extends "header.html" %}
{% block content %}

<h1>Images with just a prompt!</h1>
<p>Create your own <a href="{{ url_for('image.image_create') }}">HERE!</a></p>

{% if username %}
<p>Images created by user {{username}}:</p>
{% else %}
<p>Latest user generated images:</p>
{% endif %}
<br>

{% if images %}
{% else %}
<p>Oops! Nothing yet!</p>
{% endif %}
{% for image in images %}

<div class="gallery">
    <a href="{{ url_for('image.image_display', id=image[4]) }}">
        <img src="data:image/png;base64,{{image[2]}}" alt="{{image[0]}}" width="250" height="250">
    </a>
    <div class="desc"><b>{{image[1]}}</b></div>
    <div class="desc">By: <a href="{{ url_for('user.user_page', username=image[0]) }}">{{image[0]}}</a></div>
    <div class="desc">Created: {{image[3].strftime("%B %d, %Y at %H:%M:%S")}}</div>
</div>

{% endfor %}
{% endblock %}

flask_app/templates/image_create.html
{% extends "header.html" %}
{% block content %}

<h1>Create images with just a prompt!</h1>
<br>
{% if next_use %}
<p>Out of uses! Come back at {{next_use.strftime("%B %d, %Y at %H:%M:%S")}}</p>
{% else %}
<p>Uses left: {{ uses }}</p>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form method="POST" action="" id="form">
            {{ form.csrf_token }}
            
            <div class="form-group">
                {{ form.prompt.label(class="form-control-label") }}
                {{ form.prompt(class="form-control form-control-md bg-dark text-white") }}
        
                {% if form.prompt.errors %}
                <div class="alert alert-warning" role="alert">
                  {% for error in form.prompt.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group" id="submit-container">
                {{ form.submit(class="form-control form-control-md bg-dark text-white") }}
            </div> 
        </form>
    </div>
</div>

<script nonce="{{ csp_nonce() }}">
    window.onload = function() {
        document.getElementById('form').onsubmit = function() {
            {# I couldn't get bootstrap to work here for some reason #}
            document.getElementById('submit-container').innerHTML = '<div class="form-control form-control-md bg-dark text-white"><div class="loading mx-auto"></div></div>';
        };
    };
</script>
{% endif %}

{% endblock %}

flask_app/templates/image_display.html
{% extends "header.html" %}
{% block content %}

<h1>{{image[1]}}</h1>
<h3>By: <a href="{{ url_for('user.user_page', username=image[0]) }}">{{image[0]}}</a></h3>
<h4>Created: {{image[3].strftime("%B %d, %Y at %H:%M:%S")}}</h4>

<img src="data:image/png;base64,{{image[2]}}" alt="{{image[1]}}" width="1024" height="1024">

{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<h1>The AI Hub</h1>
<p>A space to create and share AI created images and chats using OpenAI's API and to view other users' creations.</p>
<p>Each user gets to create {{images}} images and send {{chats}} chat messages per day.</p>
<p>Register and create images <a href="{{ url_for('image.image_create') }}">here</a> and send chats <a href="{{ url_for('chat.chat_create') }}">here</a>!</p>
<footer>By: Carl Green</footer>

{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        Don't have an account? <a href="{{ url_for('user.register') }}">Register here!</a>
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form method="POST" action="">
            {{ form.csrf_token }}
            
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-md bg-dark text-white") }}
        
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                  {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% endif %}
            </div>
    
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-md bg-dark text-white") }}
        
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                  {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.submit(class="form-control form-control-md bg-dark text-white") }}
            </div> 
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/mongo_error.html
{% extends "header.html" %}
{% block content %}

<h1 class="centered">503 - Failed to Query Server Backend</h1>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        If you already have an account, <a href="{{ url_for('user.login') }}">Log In here!</a>
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-md bg-dark text-white") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-md bg-dark text-white") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-md bg-dark text-white") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-md bg-dark text-white") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-md bg-dark text-white") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

flask_app/templates/user.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h3>{{ username }}'s stuff</h3>
        <p><a href="{{ url_for('image.image', username=username) }}">Created images</a></p>
        <p><a href="{{ url_for('chat.chat', username=username) }}">Created chats</a></p>
    </div>
</div>  
{% endblock %}>